DROP TABLE IF EXISTS venue;
CREATE TABLE venue(
  id int NOT NULL AUTO_INCREMENT
  ,name   VARCHAR(255) NOT NULL PRIMARY KEY
  ,league VARCHAR(255) NOT NULL
  ,PRIMARY KEY (id)

);
INSERT INTO venue(name,league) VALUES ('American Airlines Arena','NBA');
INSERT INTO venue(name,league) VALUES ('American Airlines Center','NBA');
INSERT INTO venue(name,league) VALUES ('Amway Center','NBA');
INSERT INTO venue(name,league) VALUES ('Angel Stadium of Anaheim','MLB');
INSERT INTO venue(name,league) VALUES ('Arrowhead Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('AT&T Center','NBA');
INSERT INTO venue(name,league) VALUES ('AT&T Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Bank of America Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Bankers Life Fieldhouse','NBA');
INSERT INTO venue(name,league) VALUES ('Barclays Center','NBA');
INSERT INTO venue(name,league) VALUES ('Broncos Stadium at Mile High','NFL');
INSERT INTO venue(name,league) VALUES ('Busch Stadium','MLB');
INSERT INTO venue(name,league) VALUES ('Capital One Arena','NBA');
INSERT INTO venue(name,league) VALUES ('CenturyLink Field','NFL');
INSERT INTO venue(name,league) VALUES ('Chase Field','MLB');
INSERT INTO venue(name,league) VALUES ('Chesapeake Energy Arena','NBA');
INSERT INTO venue(name,league) VALUES ('Citi Field','MLB');
INSERT INTO venue(name,league) VALUES ('Citizens Bank Park','MLB');
INSERT INTO venue(name,league) VALUES ('Comerica Park','MLB');
INSERT INTO venue(name,league) VALUES ('Coors Field','MLB');
INSERT INTO venue(name,league) VALUES ('Dodger Stadium','MLB');
INSERT INTO venue(name,league) VALUES ('FedExField','NFL');
INSERT INTO venue(name,league) VALUES ('FedExForum','NBA');
INSERT INTO venue(name,league) VALUES ('Fenway Park','MLB');
INSERT INTO venue(name,league) VALUES ('FirstEnergy Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Fiserv Forum','NBA');
INSERT INTO venue(name,league) VALUES ('Ford Field','NFL');
INSERT INTO venue(name,league) VALUES ('Gillette Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Globe Life Park in Arlington','MLB');
INSERT INTO venue(name,league) VALUES ('Golden 1 Center','NBA');
INSERT INTO venue(name,league) VALUES ('Great American Ball Park','MLB');
INSERT INTO venue(name,league) VALUES ('Guaranteed Rate Field','MLB');
INSERT INTO venue(name,league) VALUES ('Hard Rock Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Heinz Field','NFL');
INSERT INTO venue(name,league) VALUES ('Kauffman Stadium','MLB');
INSERT INTO venue(name,league) VALUES ('Lambeau Field','NFL');
INSERT INTO venue(name,league) VALUES ('Levi''s Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Lincoln Financial Field','NFL');
INSERT INTO venue(name,league) VALUES ('Little Caesars Arena','NBA');
INSERT INTO venue(name,league) VALUES ('Los Angeles Memorial Coliseum','NFL');
INSERT INTO venue(name,league) VALUES ('Lucas Oil Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('M&T Bank Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Madison Square Garden','NBA');
INSERT INTO venue(name,league) VALUES ('Marlins Park','MLB');
INSERT INTO venue(name,league) VALUES ('Mercedes-Benz Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Mercedes-Benz Superdome','NFL');
INSERT INTO venue(name,league) VALUES ('MetLife Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Miller Park','MLB');
INSERT INTO venue(name,league) VALUES ('Minute Maid Park','MLB');
INSERT INTO venue(name,league) VALUES ('Moda Center','NBA');
INSERT INTO venue(name,league) VALUES ('Nationals Park','MLB');
INSERT INTO venue(name,league) VALUES ('New Era Field','NFL');
INSERT INTO venue(name,league) VALUES ('Nissan Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('NRG Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Oakland-Alameda County Coliseum','NFL, MLB');
INSERT INTO venue(name,league) VALUES ('Oracle Arena','NBA');
INSERT INTO venue(name,league) VALUES ('Oracle Park','MLB');
INSERT INTO venue(name,league) VALUES ('Oriole Park at Camden Yards','MLB');
INSERT INTO venue(name,league) VALUES ('Paul Brown Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Pepsi Center','NBA');
INSERT INTO venue(name,league) VALUES ('PETCO Park','MLB');
INSERT INTO venue(name,league) VALUES ('PNC Park','MLB');
INSERT INTO venue(name,league) VALUES ('Progressive Field','MLB');
INSERT INTO venue(name,league) VALUES ('Quicken Loans Arena','NBA');
INSERT INTO venue(name,league) VALUES ('Raymond James Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('Rogers Centre','MLB');
INSERT INTO venue(name,league) VALUES ('Scotiabank Arena','NBA');
INSERT INTO venue(name,league) VALUES ('Smoothie King Center','NBA');
INSERT INTO venue(name,league) VALUES ('Soldier Field','NFL');
INSERT INTO venue(name,league) VALUES ('Spectrum Center','NBA');
INSERT INTO venue(name,league) VALUES ('Staples Center','NBA');
INSERT INTO venue(name,league) VALUES ('State Farm Arena','NBA');
INSERT INTO venue(name,league) VALUES ('State Farm Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('StubHub Center','NFL');
INSERT INTO venue(name,league) VALUES ('SunTrust Park','MLB');
INSERT INTO venue(name,league) VALUES ('T-Mobile Park','MLB');
INSERT INTO venue(name,league) VALUES ('Talking Stick Resort Arena','NBA');
INSERT INTO venue(name,league) VALUES ('Target Center','NBA');
INSERT INTO venue(name,league) VALUES ('Target Field','MLB');
INSERT INTO venue(name,league) VALUES ('TD Garden','NBA');
INSERT INTO venue(name,league) VALUES ('TIAA Bank Field','NFL');
INSERT INTO venue(name,league) VALUES ('Toyota Center','NBA');
INSERT INTO venue(name,league) VALUES ('Tropicana Field','MLB');
INSERT INTO venue(name,league) VALUES ('U.S. Bank Stadium','NFL');
INSERT INTO venue(name,league) VALUES ('United Center','NBA');
INSERT INTO venue(name,league) VALUES ('Vivint Smart Home Arena','NBA');
INSERT INTO venue(name,league) VALUES ('Wells Fargo Center','NBA');
INSERT INTO venue(name,league) VALUES ('Wrigley Field','MLB');
INSERT INTO venue(name,league) VALUES ('Yankee Stadium','MLB');
